name: Git

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: Git
      - name: Pull the IP List
        run: |-
          curl https://api.github.com/meta > raw.git.txt
          foreach i ( $(cat raw.git.txt | jq 'keys[]' | grep -v ssh | grep -v verifiable_password_authentication | sed 's/"//g') ) echo "$i"; cat raw.git.txt | jq '.["'$i'"] | .[] | select(test("^([0-9]{1,3}\\.){3}"))' | sed 's/"//g' > github-$i-ipv4.txt; cat raw.git.txt | jq '.["'$i'"] | .[] | select(test("^(?:[a-fA-F0-9]{1,4}:)"))' | sed 's/"//g' > github-$i-ipv6.txt; end

      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
