name: Spamhouse

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: blob
      - name: Pull the IP List
        run: |-
          mkdir IOC
          curl https://www.spamhaus.org/drop/drop.txt | grep -v '^;' | sed -r 's|^([0-9./]*).*|\1|' > IOC/spamhouse-drop.txt
          curl https://www.spamhaus.org/drop/edrop.txt | grep -v '^;' | sed -r 's|^([0-9./]*).*|\1|' > IOC/spamhouse-edrop.txt
          curl https://www.spamhaus.org/drop/dropv6.txt | grep -v '^;' | sed -r 's|^([0-9./]*).*|\1|' > IOC/spamhouse-dropv6.txt

      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "🤖: Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
