name: MineSSLAbuseIPList

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '17 3,14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: sslabuseiplist
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Pull the Block List
        run: |-
          curl "https://sslbl.abuse.ch/blacklist/sslipblacklist.csv" -o ./temp/sslabuseiplist.txt || true
          ./scripts/sslabuse-ip-list.py ./temp/sslabuseiplist.txt "https://sslbl.abuse.ch/blacklist/sslipblacklist.csv" > sslabuseiplist.txt
      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "🤖: Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
